apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-test"
  labels:
    component: {{ .Values.app.name }}
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['{{ .Values.app.name }}-clusterip:{{ .Values.app.port }}/logo.svg']
  restartPolicy: Never