apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbit.name }}-clusterip
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.rabbit.port }}
      protocol: TCP
  selector:
    component: {{ .Values.rabbit.name }}