apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: service-app
  template:
    metadata:
      name: service-app
      labels:
        component: service-app
    spec:
      containers:
        - name: service-app
          image: antonlarichev/conv-service:1.0
          ports:
            - containerPort: 4000
          env:
            - name: AMQP_EXCHANGE
              valueFrom:
                secretKeyRef:
                  name: conv-api-secret
                  key: AMQP_EXCHANGE
            - name: AMQP_USER
              valueFrom:
                secretKeyRef:
                  name: conv-api-secret
                  key: AMQP_USER
            - name: AMQP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: conv-api-secret
                  key: AMQP_PASSWORD
            - name: AMQP_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: conv-api-secret
                  key: AMQP_HOSTNAME
            - name: AMQP_QUEUE
              valueFrom:
                secretKeyRef:
                  name: conv-api-secret
                  key: AMQP_QUEUE
          resources:
            limits:
              memory: "375Mi"
              cpu: "300m"